const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const source = fs.readFileSync(require('path').join(__dirname, '..', 'server.js'), 'utf8');
const start = source.indexOf('function calibrationBusy(');
const end = source.indexOf('function handleCalibrationRequest(', start);
const runtime = { calibration: { status: 'ready', canApply: true, revision: 3, basePpm: 66,
  suggestedPpm: 56, completedAtMs: Date.now() } };
const client = { enabled: true, state: 'CONNECTED', ppmCorrection: 66, tunerAgc: false, digitalAgc: false };
const context = { rtlClientRuntimes: new Map([['receiver', runtime]]) };
vm.createContext(context);
vm.runInContext(source.slice(start, end), context);
assert.equal(context.calibrationBusy(), false);
assert.equal(context.calibrationApplyError(client, runtime, 3, 56), null);
assert.ok(context.calibrationApplyError(client, runtime, 2, 56));
assert.ok(context.calibrationApplyError(client, runtime, 3, 57));
assert.ok(context.calibrationApplyError({ ...client, ppmCorrection: 0 }, runtime, 3, 56));
assert.ok(context.calibrationApplyError({ ...client, tunerAgc: true }, runtime, 3, 56));
assert.ok(context.calibrationApplyError({ ...client, enabled: false }, runtime, 3, 56));
runtime.calibration.method = 'gsm';
assert.equal(context.calibrationApplyError(client, runtime, 3, 56), null);
runtime.calibration.canApply = false;
assert.ok(context.calibrationApplyError(client, runtime, 3, 56));
runtime.calibration.canApply = true;
runtime.calibration.completedAtMs = Date.now() - 300001;
assert.ok(context.calibrationApplyError(client, runtime, 3, 56));
runtime.calibration.status = 'measuring';
assert.equal(context.calibrationBusy(), true);
runtime.calibration.status = 'idle';
runtime.calibrationPending = true;
assert.equal(context.calibrationBusy(), true);
console.log('FM calibration application guards and busy state passed');
